// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI_ltegJuGWSKRgp3nab5uaXU65L2w2hA',
    appId: '1:175358001868:web:a19798d6185cd1a81cf869',
    messagingSenderId: '175358001868',
    projectId: 'xaabsade-ai-5b592',
    authDomain: 'xaabsade-ai-5b592.firebaseapp.com',
    storageBucket: 'xaabsade-ai-5b592.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD42qhmt8krhJOEVm-zc0Fiuo43yh17k18',
    appId: '1:175358001868:android:d15cd7a561a76ad81cf869',
    messagingSenderId: '175358001868',
    projectId: 'xaabsade-ai-5b592',
    storageBucket: 'xaabsade-ai-5b592.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8w9_I-Yc9H1Ipn0loaXawhjIYPDn7-CY',
    appId: '1:175358001868:ios:a6a634d64a9a35a31cf869',
    messagingSenderId: '175358001868',
    projectId: 'xaabsade-ai-5b592',
    storageBucket: 'xaabsade-ai-5b592.firebasestorage.app',
    iosBundleId: 'com.example.xaabsadeAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8w9_I-Yc9H1Ipn0loaXawhjIYPDn7-CY',
    appId: '1:175358001868:ios:a6a634d64a9a35a31cf869',
    messagingSenderId: '175358001868',
    projectId: 'xaabsade-ai-5b592',
    storageBucket: 'xaabsade-ai-5b592.firebasestorage.app',
    iosBundleId: 'com.example.xaabsadeAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI_ltegJuGWSKRgp3nab5uaXU65L2w2hA',
    appId: '1:175358001868:web:bd809272ed20ebc81cf869',
    messagingSenderId: '175358001868',
    projectId: 'xaabsade-ai-5b592',
    authDomain: 'xaabsade-ai-5b592.firebaseapp.com',
    storageBucket: 'xaabsade-ai-5b592.firebasestorage.app',
  );
}
